### PR TITLE
Fixed: 'ansible_user' is undefined"

### PR DESCRIPTION
**Pull request by edmargomes**
fatal: [default]: FAILED! => {"failed": true, "msg": "the field 'become_user' has an invalid value, which appears to include a variable that is undefined. The error was: {{ ansible_user }}: 'ansible_user' is undefined"}

### CODE REVIEW

**Comment by geerlingguy** [comment]
@edmargomes - Rather, `ansible_ssh_user` was deprecated in Ansible 2.0+ (see http://docs.ansible.com/ansible/intro_inventory.html).

> Ansible 2.0 has deprecated the “ssh” from ansible_ssh_user, ansible_ssh_host, and ansible_ssh_port to become ansible_user, ansible_host, and ansible_port. If you are using a version of Ansible prior to 2.0, you should continue using the older style variables (ansible_ssh_*). These shorter variables are ignored, without warning, in older versions of Ansible.

**Comment by geerlingguy** [comment]
Note that this role requires Ansible 2.0+: https://github.com/geerlingguy/ansible-role-ruby/blob/master/meta/main.yml#L9

**Comment by edmargomes** [comment]
Thanks @geerlingguy !!!

**Comment by geerlingguy** [comment]
Sure thing!

**Pull request closed without merging**
